var pokemons = {
        names: [
          {
            name: "Charizard",
            type: "Flying, Fire",
            weakness: "Electric, Water, Rock",
            wclass: "weakness weakness-electric weakness-water weakness-rock",
            ability: "Blaze",
            evolvesFrom: "Charmeleon",
            image:"charizard.png",
            flying: "<i style='color:green' class='fas fa-check-square'></i>",
            class: "type flying fire",
            flies: "yes",
            description:"Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself",
            height: "5' 07\"",
            weight: "199.5lbs",
            category: "Flame",
            gender: '<i class="fas fa-mars" style="font-size: 30px;"></i> <i class="fas fa-venus" style="font-size: 30px;"></i>',
            cardsImages:["img/charizard_card_1.png", "img/charizard_card_2.png", "img/charizard_card_3.png"]
          },
          {
            name: "Charmeleon",
            type: "Fire",
            class: "type fire",
            ability:"Blaze",
            weakness: "Water, Ground, Rock",
            wclass: "weakness weakness-water weakness-ground weakness-rock",
            evolvesFrom:"Charmander",
            evolvesTo:"Charizard",
            flies: "no",
            image: "charmeleon.png",
            description:"Charmeleon mercilessly destroys its foes using its sharp claws. If it encounters a strong foe, it turns aggressive. In this excited state, the flame at the tip of its tail flares with a bluish white color",
            height: "3' 07\"",
            weight: "41.9 lbs",
            category: "Flame",
            gender: '<i class="fas fa-mars" style="font-size: 30px;"></i> <i class="fas fa-venus" style="font-size: 30px;"></i>',
            cardsImages:["img/charmeleon_card_1.png", "img/charmeleon_card_2.png", "img/charmeleon_card_3.png"]
          },
          {
          name: "Charmander",
          type: "Fire",
          class: "type fire",
          wclass: "weakness weakness-water weakness-ground weakness-rock",
          ability:"Blaze",
          weakness: "Water, Ground, Rock",
          evolvesTo:"Charmeleon",
          image: "charmander.png",
          flies: "no",
          description: "The flame that burns at the tip of its tail is an indication of its emotions. The flame wavers when Charmander is enjoying itself. If the Pokémon becomes enraged, the flame burns fiercely.",
          height: "2' 00\"",
          weight: "18.7lbs",
          category: "Lizard",
          gender: '<i class="fas fa-mars" style="font-size: 30px;"></i> <i class="fas fa-venus" style="font-size: 30px;"></i>',
          cardsImages:["img/charmander_card_1.png", "img/charmander_card_2.png", "img/charmander_card_3.png"]
          }, 
          {
            name: "Bulbasaur",
            type: "Grass, Poison",
            class: "type grass poison",
            ability:"Overgrow",
            weakness: "Psychic, Ice, Flying, Fire",
            wclass: "weakness weakness-psychic weakness-ice weakness-flying weakness-fire",
            flies: "no",
            evolvesTo:"Ivysaur",
            image: "bulbasaur.png",
            description:"Bulbasaur can be seen napping in bright sunlight. There is a seed on its back. By soaking up the sun's rays, the seed grows progressively larger.",
            height: "2' 04\"",
            weight: "15.2 lbs",
            category: "Seed",
            gender: '<i class="fas fa-mars" style="font-size: 30px;"></i> <i class="fas fa-venus" style="font-size: 30px;"></i>',
            cardsImages:["img/bulbasaur_card_1.png", "img/bulbasaur_card_2.png", "img/bulbasaur_card_3.png"]
          }, {
            name: "Blastoise",
            type: "Water",
            class: "type water",
            ability:"Torrent",
            wclass: "weakness weakness-electric weakness-grass",
            weakness: "Electric, Grass",
            image: "blastoise.png",
            evolvesFrom:"Wartortle",
            flies: "no",
            description:"Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself",
            height: "5' 07\"",
            weight: "199.5lbs",
            category: "Flame",
            gender: '<i class="fas fa-mars" style="font-size: 30px;"></i> <i class="fas fa-venus" style="font-size: 30px;"></i>',
            cardsImages:["img/blastoise_card_1.png", "img/blastoise_card_2.png", "img/blastoise_card_3.png"]
          }, {
            name: "Celebi",
            type: "Psychic, Grass",
            wclass: "weakness weakness-dark weakness-bug weakness-ice weakness-poison weakness-flying weakness-fire weakness-ghost",
            class: "type psychic grass",
            ability:"Natural Cure",
            weakness: "Dark, Bug, Ice, Poison, Flying, Fire, Ghost",
            flying: "<i style='color:green' class='fas fa-check-square'></i>",
            flies: "no",
            image: "celebi.png",
            description:"Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself",
            height: "5' 07\"",
            weight: "199.5lbs",
            category: "Flame",
            gender: '<i class="fas fa-mars" style="font-size: 30px;"></i> <i class="fas fa-venus" style="font-size: 30px;"></i>',
            cardsImages:["img/blastoise_card_1.png", "img/blastoise_card_2.png", "img/blastoise_card_3.png"]
          },{
            name: "Dragonite",
            type: "Flying, Dragon",
            class: "type flying dragon",
            wclass: "weakness weakness-rock weakness-ice weakness-dragon weakness-fairy",
            ability:"Inner Focus",
            weakness: "Rock, Ice, Dragon, Fairy",
            evolesFrom:"Dragonair",
            image: "dragonite.png",
            flies: "yes",
            description:"Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself",
            height: "5' 07\"",
            weight: "199.5lbs",
            category: "Flame",
            gender: '<i class="fas fa-mars" style="font-size: 30px;"></i> <i class="fas fa-venus" style="font-size: 30px;"></i>',
            cardsImages:["img/blastoise_card_1.png", "img/blastoise_card_2.png", "img/blastoise_card_3.png"]
          },{
            name: "Eevee",
            type: "Normal",
            class: "type normal",
            ability:"Adaptability, Run Away",
            wclass: "weakness weakness-fighting",
            emojiType: "<i class='fas fa-fire'></i>",
            weakness: "Fighting",
            evolvesTo:"Espeon, Umbreon, Sylveon, Vaporeon, Flareon, Jolteon, Leafeon, Glaceon",
            flies: "no",
            image: "eevee.png",
            description:"Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself",
            height: "5' 07\"",
            weight: "199.5lbs",
            category: "Flame",
            gender: '<i class="fas fa-mars" style="font-size: 30px;"></i> <i class="fas fa-venus" style="font-size: 30px;"></i>',
            cardsImages:["img/blastoise_card_1.png", "img/blastoise_card_2.png", "img/blastoise_card_3.png"]
          },{
            name: "Pichu",
            type: "Electric",
            class: "type electric",
            wclass: "weakness weakness-ground",
            ability:"Static",
            weakness: "Ground",
            flies: "no",
            image: "pichu.png",
            evolvesTo:"Pikachu",
            description:"Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself",
            height: "5' 07\"",
            weight: "199.5lbs",
            category: "Flame",
            gender: '<i class="fas fa-mars" style="font-size: 30px;"></i> <i class="fas fa-venus" style="font-size: 30px;"></i>',
            cardsImages:["img/blastoise_card_1.png", "img/blastoise_card_2.png", "img/blastoise_card_3.png"]
          },{
            name: "Ditto",
            type: "Normal",
            wclass: "weakness weakness-fighting",
            class: "type normal",
            ability:"Limber",
            abilityHidden:"Imposter",
            flies: "no",
            weakness: "Fighting",
            image: "ditto.png",
            description:"Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself",
            height: "5' 07\"",
            weight: "199.5lbs",
            category: "Flame",
            gender: '<i class="fas fa-mars" style="font-size: 30px;"></i> <i class="fas fa-venus" style="font-size: 30px;"></i>',
            cardsImages:["img/blastoise_card_1.png", "img/blastoise_card_2.png", "img/blastoise_card_3.png"]
          },{
            name: "Gengar",
            type: "Poison, Ghost",
            wclass: "weakness weakness-psychic weakness-dark weakness-ghost",
            class: "type poison ghost",
            abiliy:"Cursed Body, Levitate",
            weakness: "Psychic, Dark, Ghost",
            flies: "no",
            image: "gengar.png",
            evolesFrom:"Haunter",
            description:"Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself",
            height: "5' 07\"",
            weight: "199.5lbs",
            category: "Flame",
            gender: '<i class="fas fa-mars" style="font-size: 30px;"></i> <i class="fas fa-venus" style="font-size: 30px;"></i>',
            cardsImages:["img/blastoise_card_1.png", "img/blastoise_card_2.png", "img/blastoise_card_3.png"]
          },
          {
            name: "Magikarp",
            class: "type water",
            type: "Water",
            wclass: "weakness weakness-electric weakness-grass",
            ability:"Swift Swim",
            weakness: "Electric, Grass",
            flies: "no",
            evolvesTo:"Gyarados",
            image: "magikarp.png",
            description:"Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself",
            height: "5' 07\"",
            weight: "199.5lbs",
            category: "Flame",
            gender: '<i class="fas fa-mars" style="font-size: 30px;"></i> <i class="fas fa-venus" style="font-size: 30px;"></i>',
            cardsImages:["img/blastoise_card_1.png", "img/blastoise_card_2.png", "img/blastoise_card_3.png"]
          },
          {
            name: "Jigglypuff",
            type: "Normal, Fairy",
            class: "type normal fairy",
            wclass: "weakness weakness-poison weakness-steel",
            ability:"Cute Charm, Competitive",
            weakness: "Poison, Steel",
            flies: "no",
            evolvesFrom:"Igglybuff",
            evolvesTo:"Wigglytuff",
            image: "jigglypuff.png",
            description:"Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself",
            height: "5' 07\"",
            weight: "199.5lbs",
            category: "Flame",
            gender: '<i class="fas fa-mars" style="font-size: 30px;"></i> <i class="fas fa-venus" style="font-size: 30px;"></i>'
          },
          {
            name: "Mew",
            type: "Psychic",
            class: "type psychic",
            wclass: "weakness weakness-dark weakness-bug weakness-ghost",
            flies: "no",
            abiliy:"Synchronize",
            weakness: "Dark, Bug, Ghost",
            image: "mew.png",
            description:"Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself",
            height: "5' 07\"",
            weight: "199.5lbs",
            category: "Flame",
            gender: '<i class="fas fa-mars" style="font-size: 30px;"></i> <i class="fas fa-venus" style="font-size: 30px;"></i>',
            cardsImages:["img/blastoise_card_1.png", "img/blastoise_card_2.png", "img/blastoise_card_3.png"]
          },
          {
            name: "Mewtwo",
            type: "Psychic",
            class: "type psychic",
            wclass: "weakness weakness-dark weakness-bug weakness-ghost",
            ability:"Pressure",
            weakness: "Dark, Bug, Ghost",
            image: "mewtwo.png",
            description:"Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself",
            height: "5' 07\"",
            weight: "199.5lbs",
            category: "Flame",
            gender: '<i class="fas fa-mars" style="font-size: 30px;"></i> <i class="fas fa-venus" style="font-size: 30px;"></i>',
            cardsImages:["img/blastoise_card_1.png", "img/blastoise_card_2.png", "img/blastoise_card_3.png"]
          },
          {
            name: "Raichu",
            type: "Electric",
            class: "type electric",
            wclass: "weakness weakness-ground",
            ability:"Static",
            flies: "no",
            weakness: "Ground",
            image: "raichu.png",
            evolesFrom:"Pikachu",
            description:"Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself",
            height: "5' 07\"",
            weight: "199.5lbs",
            category: "Flame",
            gender: '<i class="fas fa-mars" style="font-size: 30px;"></i> <i class="fas fa-venus" style="font-size: 30px;"></i>',
            cardsImages:["img/blastoise_card_1.png", "img/blastoise_card_2.png", "img/blastoise_card_3.png"]
          }, 
          {
            name: "Pikachu",
            type: "Electric",
            wclass: "weakness weakness-ground",
            class: "type electric",
            ability:"Static",
            flies: "no",
            weakness: "Ground",
            image: "pikachu.png",
            evolesFrom:"Pichu",
            description:"Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself",
            height: "5' 07\"",
            weight: "199.5lbs",
            category: "Flame",
            gender: '<i class="fas fa-mars" style="font-size: 30px;"></i> <i class="fas fa-venus" style="font-size: 30px;"></i>',
            cardsImages:["img/blastoise_card_1.png", "img/blastoise_card_2.png", "img/blastoise_card_3.png"]
          },  
          {
            name: "Snorlax",
            type: "Normal",
            wclass: "weakness weakness-fighting",
            class: "type normal",
            ability:"Thick Fat, Immunity",
            flies: "no",
            weakness: "Fighting",
            image: "snorlax.png",
            evolesFrom:"Munchlax",
            description:"Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself",
            height: "5' 07\"",
            weight: "199.5lbs",
            category: "Flame",
            gender: '<i class="fas fa-mars" style="font-size: 30px;"></i> <i class="fas fa-venus" style="font-size: 30px;"></i>'
          },        
          {
            name: "Lapras",
            type: "Water, Ice",
            wclass: "weakness weakness-eletric weakness-rock weakness-grass weakness-fighting",
            class: "type normal",
            ability:"Shell Armor, Water Absorb",
            weakness: "Electric, Rock, Grass, Fighting",
            flies: "no",
            image: "lapras.png",
            description:"Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself",
            height: "5' 07\"",
            weight: "199.5lbs",
            category: "Flame",
            gender: '<i class="fas fa-mars" style="font-size: 30px;"></i> <i class="fas fa-venus" style="font-size: 30px;"></i>',
            cardsImages:["img/blastoise_card_1.png", "img/blastoise_card_2.png", "img/blastoise_card_3.png"]
          },  
          {
            name: "Gyarados",
            type: "Water, Flying",
            class: "type normal",
            wclass: "weakness weakness-eletric weakness-rock",
            flies: "no",
            ability:"Intimidate",
            weakness: "Electric, Rock",
            image: "gyarados.png",
            evolvesFrom: "Magikarp",
            description:"Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself",
            height: "5' 07\"",
            weight: "199.5lbs",
            category: "Flame",
            gender: '<i class="fas fa-mars" style="font-size: 30px;"></i> <i class="fas fa-venus" style="font-size: 30px;"></i>',
            cardsImages:["img/blastoise_card_1.png", "img/blastoise_card_2.png", "img/blastoise_card_3.png"]
          },
        ]
      };


