var pokemons = {
        names: [
          {
            name: "Charizard",
            type: "Flying, Fire",
            weakness: "Electric, Water, Rock",
            wclass: "weakness weakness-electric weakness-water weakness-rock",
            ability: "Blaze",
            evolvesFrom: "Charmeleon",
            image:"charizard.png",
            flying: "<i style='color:green' class='fas fa-check-square'></i>",
            class: "type flying fire",
            flies: "yes",
            description:"Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself",
            height: "5' 07\"",
            weight: "199.5lbs",
            category: "Flame",
            gender: 'M/F',
            cardsImages:["img/charizard_card_1.png", "img/charizard_card_2.png", "img/charizard_card_3.png"]
          },
          {
            name: "Charmeleon",
            type: "Fire",
            class: "type fire",
            ability:"Blaze",
            weakness: "Water, Ground, Rock",
            wclass: "weakness weakness-water weakness-ground weakness-rock",
            evolvesFrom:"Charmander",
            evolvesTo:"Charizard",
            flies: "no",
            image: "charmeleon.png",
            description:"Charmeleon mercilessly destroys its foes using its sharp claws. If it encounters a strong foe, it turns aggressive. In this excited state, the flame at the tip of its tail flares with a bluish white color",
            height: "3' 07\"",
            weight: "41.9 lbs",
            category: "Flame",
            gender: 'M/F',
            cardsImages:["img/charmeleon_card_1.png", "img/charmeleon_card_2.png", "img/charmeleon_card_3.png"]
          },
          {
          name: "Charmander",
          type: "Fire",
          class: "type fire",
          wclass: "weakness weakness-water weakness-ground weakness-rock",
          ability:"Blaze",
          weakness: "Water, Ground, Rock",
          evolvesTo:"Charmeleon",
          image: "charmander.png",
          flies: "no",
          description: "The flame that burns at the tip of its tail is an indication of its emotions. The flame wavers when Charmander is enjoying itself. If the Pokémon becomes enraged, the flame burns fiercely.",
          height: "2' 00\"",
          weight: "18.7lbs",
          category: "Lizard",
          gender: 'M/F',
          cardsImages:["img/charmander_card_1.png", "img/charmander_card_2.png", "img/charmander_card_3.png"]
          }, 
          {
            name: "Bulbasaur",
            type: "Grass, Poison",
            class: "type grass poison",
            ability:"Overgrow",
            weakness: "Psychic, Ice, Flying, Fire",
            wclass: "weakness weakness-psychic weakness-ice weakness-flying weakness-fire",
            flies: "no",
            evolvesTo:"Ivysaur",
            image: "bulbasaur.png",
            description:"Bulbasaur can be seen napping in bright sunlight. There is a seed on its back. By soaking up the sun's rays, the seed grows progressively larger.",
            height: "2' 04\"",
            weight: "15.2 lbs",
            category: "Seed",
            gender: 'M/F',
            cardsImages:["img/bulbasaur_card_1.png", "img/bulbasaur_card_2.png", "img/bulbasaur_card_3.png"]
          }, {
            name: "Blastoise",
            type: "Water",
            class: "type water",
            ability:"Torrent",
            wclass: "weakness weakness-electric weakness-grass",
            weakness: "Electric, Grass",
            image: "blastoise.png",
            evolvesFrom:"Wartortle",
            flies: "no",
            description:"Blastoise has water spouts that protrude from its shell. The water spouts are very accurate. They can shoot bullets of water with enough accuracy to strike empty cans from a distance of over 160 feet.",
            height: "5' 03\"",
            weight: "188.5lbs",
            category: "Shellfish",
            gender: 'M/F',
            cardsImages:["img/blastoise_card_1.png", "img/blastoise_card_2.png", "img/blastoise_card_3.png"]
          }, {
            name: "Celebi",
            type: "Psychic, Grass",
            wclass: "weakness weakness-dark weakness-bug weakness-ice weakness-poison weakness-flying weakness-fire weakness-ghost",
            class: "type psychic grass",
            ability:"Natural Cure",
            weakness: "Dark, Bug, Ice, Poison, Flying, Fire, Ghost",
            flying: "<i style='color:green' class='fas fa-check-square'></i>",
            flies: "no",
            image: "celebi.png",
            description:"This Pokémon came from the future by crossing over time. It is thought that so long as Celebi appears, a bright and shining future awaits us.",
            height: "2' 07\"",
            weight: "11.0lbs",
            category: "Time Travelcle",
            gender: 'M/F',
            cardsImages:["img/celebi_card_1.png", "img/celebi_card_2.png", "img/celebi_card_3.png"]
          },{
            name: "Dragonite",
            type: "Flying, Dragon",
            class: "type flying dragon",
            wclass: "weakness weakness-rock weakness-ice weakness-dragon weakness-fairy",
            ability:"Inner Focus",
            weakness: "Rock, Ice, Dragon, Fairy",
            evolesFrom:"Dragonair",
            image: "dragonite.png",
            flies: "yes",
            description:"Dragonite is capable of circling the globe in just 16 hours. It is a kindhearted Pokémon that leads lost and foundering ships in a storm to the safety of land.",
            height: "7' 03\"",
            weight: "483.0lbs",
            category: "Dragon",
            gender: 'M/F',
            cardsImages:["img/dragonite_card_1.png", "img/dragonite_card_2.png", "img/dragonite_card_3.png"]
          },{
            name: "Eevee",
            type: "Normal",
            class: "type normal",
            ability:"Adaptability, Run Away",
            wclass: "weakness weakness-fighting",
            emojiType: "<i class='fas fa-fire'></i>",
            weakness: "Fighting",
            evolvesTo:"Espeon, Umbreon, Sylveon, Vaporeon, Flareon, Jolteon, Leafeon, Glaceon",
            flies: "no",
            image: "eevee.png",
            description:"Eevee has an unstable genetic makeup that suddenly mutates due to the environment in which it lives. Radiation from various stones causes this Pokémon to evolve",
            height: "1' 00\"",
            weight: "14.3 lbs",
            category: "Evolution",
            gender: 'M/F',
            cardsImages:["img/eevee_card_1.png", "img/eevee_card_2.png", "img/eevee_card_3.png"]
          },{
            name: "Pichu",
            type: "Electric",
            class: "type electric",
            wclass: "weakness weakness-ground",
            ability:"Static",
            weakness: "Ground",
            flies: "no",
            image: "pichu.png",
            evolvesTo:"Pikachu",
            description:"Pichu charges itself with electricity more easily on days with thunderclouds or when the air is very dry. You can hear the crackling of static electricity coming off this Pokémon.",
            height: "1' 00\"",
            weight: "4.4 lbs",
            category: "Tiny Mouse",
            gender: 'M/F',
            cardsImages:["img/pichu_card_1.png", "img/pichu_card_2.png", "img/pichu_card_3.png"]
          },{
            name: "Ditto",
            type: "Normal",
            wclass: "weakness weakness-fighting",
            class: "type normal",
            ability:"Limber",
            abilityHidden:"Imposter",
            flies: "no",
            weakness: "Fighting",
            image: "ditto.png",
            description:"Ditto rearranges its cell structure to transform itself into other shapes. However, if it tries to transform itself into something by relying on its memory, this Pokémon manages to get details wrong.",
            height: "1' 00\"",
            weight: "8.8 lbs",
            category: "Transform",
            gender: 'Unknown',
            cardsImages:["img/ditto_card_1.png", "img/ditto_card_2.png", "img/ditto_card_3.png"]
          },{
            name: "Gengar",
            type: "Poison, Ghost",
            wclass: "weakness weakness-psychic weakness-dark weakness-ghost",
            class: "type poison ghost",
            abiliy:"Cursed Body, Levitate",
            weakness: "Psychic, Dark, Ghost",
            flies: "no",
            image: "gengar.png",
            evolesFrom:"Haunter",
            description:"Sometimes, on a dark night, your shadow thrown by a streetlight will suddenly and startlingly overtake you. It is actually a Gengar running past you, pretending to be your shadow.",
            height: "4' 11\"",
            weight: "89.5 lbs",
            category: "Shadow",
            gender: 'M/F',
            cardsImages:["img/gengar_card_1.png", "img/gengar_card_2.png", "img/gengar_card_3.png"]
          },
          {
            name: "Magikarp",
            class: "type water",
            type: "Water",
            wclass: "weakness weakness-electric weakness-grass",
            ability:"Swift Swim",
            weakness: "Electric, Grass",
            flies: "no",
            evolvesTo:"Gyarados",
            image: "magikarp.png",
            description:"Magikarp is a pathetic excuse for a Pokémon that is only capable of flopping and splashing. This behavior prompted scientists to undertake research into it.",
            height: "2' 11\"",
            weight: "22.0 lbs",
            category: "Fish",
            gender: 'M/F',
            cardsImages:["img/magikarp_card_1.png", "img/magikarp_card_2.png", "img/magikarp_card_3.png"]
          },
          {
            name: "Jigglypuff",
            type: "Normal, Fairy",
            class: "type normal fairy",
            wclass: "weakness weakness-poison weakness-steel",
            ability:"Cute Charm, Competitive",
            weakness: "Poison, Steel",
            flies: "no",
            evolvesFrom:"Igglybuff",
            evolvesTo:"Wigglytuff",
            image: "jigglypuff.png",
            description:"Jigglypuff's vocal cords can freely adjust the wavelength of its voice. This Pokémon uses this ability to sing at precisely the right wavelength to make its foes most drowsy.",
            height: "1' 08\"",
            weight: "12.1 lbs",
            category: "Balloon",
            gender: 'M/F',
            cardsImages:["img/jigglypuff_card_1.png", "img/jigglypuff_card_2.png", "img/jigglypuff_card_3.png"]
          },
          {
            name: "Mew",
            type: "Psychic",
            class: "type psychic",
            wclass: "weakness weakness-dark weakness-bug weakness-ghost",
            flies: "no",
            abiliy:"Synchronize",
            weakness: "Dark, Bug, Ghost",
            image: "mew.png",
            description:"Mew is said to possess the genetic composition of all Pokémon. It is capable of making itself invisible at will, so it entirely avoids notice even if it approaches people.",
            height: "1' 04\"",
            weight: "8.8 lbs",
            category: "New Species",
            gender: 'Unknown',
            cardsImages:["img/mew_card_1.png", "img/mew_card_2.png", "img/mew_card_3.png"]
          },
          {
            name: "Mewtwo",
            type: "Psychic",
            class: "type psychic",
            wclass: "weakness weakness-dark weakness-bug weakness-ghost",
            ability:"Pressure",
            weakness: "Dark, Bug, Ghost",
            image: "mewtwo.png",
            description:"Mewtwo is a Pokémon that was created by genetic manipulation. However, even though the scientific power of humans created this Pokémon's body, they failed to endow Mewtwo with a compassionate heart.",
            height: "6' 07\"",
            weight: "269.0 lbs",
            category: "Genetic",
            gender: 'Unknown',
            cardsImages:["img/mewtwo_card_1.png", "img/mewtwo_card_2.png", "img/mewtwo_card_3.png"]
          },
          {
            name: "Raichu",
            type: "Electric",
            class: "type electric",
            wclass: "weakness weakness-ground",
            ability:"Static",
            flies: "no",
            weakness: "Ground",
            image: "raichu.png",
            evolesFrom:"Pikachu",
            description:"If the electrical sacs become excessively charged, Raichu plants its tail in the ground and discharges. Scorched patches of ground will be found near this Pokémon's nest.",
            height: "2' 07\"",
            weight: "66.1 lbs",
            category: "Mouse",
            gender: 'M/F',
            cardsImages:["img/raichu_card_1.png", "img/raichu_card_2.png", "img/raichu_card_3.png"]
          }, 
          {
            name: "Pikachu",
            type: "Electric",
            wclass: "weakness weakness-ground",
            class: "type electric",
            ability:"Static",
            flies: "no",
            weakness: "Ground",
            image: "pikachu.png",
            evolesFrom:"Pichu",
            description:"Whenever Pikachu comes across something new, it blasts it with a jolt of electricity. If you come across a blackened berry, it's evidence that this Pokémon mistook the intensity of its charge.",
            height: "1' 04\"",
            weight: "13.2 lbs",
            category: "Mouse",
            gender: 'M/F',
            cardsImages:["img/pikachu_card_1.png", "img/pikachu_card_2.png", "img/pikachu_card_3.png"]
          },  
          {
            name: "Snorlax",
            type: "Normal",
            wclass: "weakness weakness-fighting",
            class: "type normal",
            ability:"Thick Fat, Immunity",
            flies: "no",
            weakness: "Fighting",
            image: "snorlax.png",
            evolesFrom:"Munchlax",
            description:"Snorlax's typical day consists of nothing more than eating and sleeping. It is such a docile Pokémon that there are children who use its expansive belly as a place to play.",
            height: "6' 11\"",
            weight: "1014.0 lbs",
            category: "Sleeping",
            gender: 'M',
            cardsImages:["img/snorlax_card_1.png", "img/snorlax_card_2.png", "img/snorlax_card_3.png"]
          },        
          {
            name: "Lapras",
            type: "Water, Ice",
            wclass: "weakness weakness-eletric weakness-rock weakness-grass weakness-fighting",
            class: "type normal",
            ability:"Shell Armor, Water Absorb",
            weakness: "Electric, Rock, Grass, Fighting",
            flies: "no",
            image: "lapras.png",
            description:"People have driven Lapras almost to the point of extinction. In the evenings, this Pokémon is said to sing plaintively as it seeks what few others of its kind still remain.",
            height: "8' 02\"",
            weight: "485.0 lbs",
            category: "Transport",
            gender: 'M/F',
            cardsImages:["img/lapras_card_1.png", "img/lapras_card_2.png", "img/lapras_card_3.png"]
          },  
          {
            name: "Gyarados",
            type: "Water, Flying",
            class: "type normal",
            wclass: "weakness weakness-eletric weakness-rock",
            flies: "no",
            ability:"Intimidate",
            weakness: "Electric, Rock",
            image: "gyarados.png",
            evolvesFrom: "Magikarp",
            description:"When Magikarp evolves into Gyarados, its brain cells undergo a structural transformation. It is said that this transformation is to blame for this Pokémon's wildly violent nature.",
            height: "21' 04\"",
            weight: "518.1 lbs",
            category: "Atrocious",
            gender: 'M',
            cardsImages:["img/gyarados_card_1.png", "img/gyarados_card_2.png", "img/gyarados_card_3.png"]
          },
        ]
      };


